---
php_ini:
 - option: "engine"
   section: "PHP"
   value: "1"
 - option: "error_reporting"
   section: "PHP"
   value: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
 - option: "ldap.max_links"
   section: "ldap"
   value: "1"
 - option: "display_errors"
   section: "PHP"
   value: "On"
 - option: "html_errors"
   section: "PHP"
   value: "On"
