---
php_ini:
 - option: "engine"
   section: "PHP"
   value: "1"
 - option: "error_reporting"
   section: "PHP"
   value: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
 - option: "ldap.max_links"
   section: "ldap"
   value: "1"
 - option: "display_errors"
   section: "PHP"
   value: "On"
 - option: "html_errors"
   section: "PHP"
   value: "On"
apache_vhosts:
  - servername: "local.dev"
    documentroot: "/app/public"
    ssl: true
    ssl_redirect: false
    extra_parameters:
     - 'SSLCertificateFile /app/public/ca.crt'
     - 'SSLCertificateKeyFile /app/public/ca.key'
     # testing for local signed client certificates
     - 'SSLCACertificateFile /app/public/ca.crt'
     - 'SSLCADNRequestFile /app/public/ca.crt'
     - 'SSLVerifyClient optional'
     - 'SSLVerifyDepth 1'
     - 'SSLOptions +StdEnvVars'
